(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function options(selected=''){return `<option value="" disabled ${selected?'':'selected'}>Choose who pays this bill</option>${(members||[]).map(m=>`<option value="${m.id}" ${m.id===selected?'selected':''}>${safe(m.display_name)}</option>`).join('')}`}
function payerName(id){return (members||[]).find(m=>m.id===id)?.display_name||'Unknown'}
function openBill(id=null){
 const b=(bills||[]).find(x=>x.id===id);
 modal(`<p class="kicker">BILL TRACKER</p><h2>${b?'Edit bill':'Add bill'}</h2><p class="card-note">Every bill must be assigned to a household member.</p><form class="form" id="requiredBillForm"><label>Bill name<input name="name" required maxlength="100" value="${safe(b?.name||'')}" placeholder="Phone bill"></label><label>Total amount<input name="amount" type="number" min="0.01" step="0.01" required value="${b?.amount??''}"></label><label>Who pays this bill? <span style="color:#b43a42">*</span><select name="payer" required>${options(b?.payer_user_id||b?.user_id||'')}</select></label><label>Frequency<select name="frequency"><option value="monthly" ${b?.frequency==='monthly'?'selected':''}>Monthly</option><option value="weekly" ${b?.frequency==='weekly'?'selected':''}>Weekly</option><option value="yearly" ${b?.frequency==='yearly'?'selected':''}>Yearly</option></select></label><label>Amount already paid<input name="paid" type="number" min="0" step="0.01" value="${Number(b?.paid_amount)||0}"></label><label>Tag<input name="tag" maxlength="60" value="${safe(b?.tag||'')}" placeholder="Utilities, Phone, Rent..."></label><div class="form-actions"><button class="primary" id="saveRequiredBill">${b?'Save Changes':'Add Bill'}</button></div></form>`);
 const f=q('#requiredBillForm');
 f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f),payer=d.get('payer');if(!payer)return toast('Choose who pays this bill.');const total=Number(d.get('amount')),paid=Math.min(total,Math.max(0,Number(d.get('paid'))||0)),status=paid>=total?'paid':paid>0?'partially_paid':'unpaid',payload={household_id:profile.household_id,user_id:b?.user_id||session.user.id,payer_user_id:payer,name:d.get('name').trim(),amount:total,frequency:d.get('frequency'),paid_amount:paid,payment_status:status,tag:d.get('tag')?.trim()||null};const btn=q('#saveRequiredBill');btn.disabled=true;btn.textContent='Saving…';const r=b?await sb.from('bills').update(payload).eq('id',b.id):await sb.from('bills').insert(payload);if(r.error){btn.disabled=false;btn.textContent=b?'Save Changes':'Add Bill';return toast(r.error.message)}close();await loadData();toast(b?'Bill updated.':'Bill added.')};
}
function annotate(){qa('#billList .hf-bill-card').forEach(row=>{const edit=row.querySelector('[data-bill-edit2]'),b=edit?(bills||[]).find(x=>x.id===edit.dataset.billEdit2):null;if(!b)return;let badge=row.querySelector('.bill-payer-badge');if(!badge){badge=document.createElement('small');badge.className='bill-payer-badge';const title=row.querySelector('.hf-bill-title')?.parentElement;title?.appendChild(badge)}if(badge)badge.textContent=`Paid by ${payerName(b.payer_user_id||b.user_id)}`})}
document.addEventListener('click',e=>{const add=e.target.closest('#addBillBtn');if(add){e.preventDefault();e.stopImmediatePropagation();openBill();return}const edit=e.target.closest('[data-bill-edit2]');if(edit){e.preventDefault();e.stopImmediatePropagation();openBill(edit.dataset.billEdit2)}},true);
const css=document.createElement('style');css.textContent='.bill-payer-badge{display:inline-block;margin-top:4px;font-size:8px!important;font-weight:800;color:#355a7a;background:#edf4fb;border-radius:999px;padding:4px 7px}';document.head.appendChild(css);
window.addEventListener('load',()=>setTimeout(annotate,1300));setInterval(()=>{if(q('#bills.active'))annotate()},1800);
})();