(()=>{
const q=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=()=>`hf-card-${session?.user?.id||'guest'}`;function prefs(){try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}}function save(x){localStorage.setItem(key(),JSON.stringify({...prefs(),...x}))}
function fakeNumber(){const a=Array.from({length:12},()=>Math.floor(Math.random()*10)).join('');return `9900${a}`}
function decorate(){const card=q('.bank-card');if(!card||card.dataset.fun)return;card.dataset.fun='1';card.classList.add('hf-flip-card');const original=card.innerHTML;card.innerHTML=`<div class="hf-card-inner"><div class="hf-card-face hf-card-front">${original}</div><div class="hf-card-face hf-card-back"><div class="magstripe"></div><p>HOMEFUND HOUSEHOLD CARD</p><b id="hfBackNumber">SIMULATED</b><small>For HomeFund tracking only • Not for payment</small><button class="hf-mini" id="hfFlipBack">Flip to front</button></div></div>`;card.onclick=e=>{if(e.target.closest('button'))return;card.classList.toggle('flipped')};q('#hfFlipBack').onclick=e=>{e.stopPropagation();card.classList.remove('flipped')};applyPrefs();}
function applyPrefs(){const p=prefs(),card=q('.bank-card');if(!card)return;card.dataset.theme=p.theme||'navy';const name=q('.hf-card-front .card-bottom b');if(name)name.textContent=(profile?.display_name||'MEMBER').toUpperCase();const n=p.number||fakeNumber();if(!p.number)save({number:n});const last=n.slice(-4);const dig=q('.hf-card-front .digits');if(dig)dig.innerHTML=`•••• &nbsp;•••• &nbsp;•••• &nbsp;${last}`;if(q('#hfBackNumber'))q('#hfBackNumber').textContent=`HOMEFUND • ${n.match(/.{1,4}/g).join(' ')}`;}
function designer(){const p=prefs();modal(`<p class="kicker">CARD STUDIO</p><h2>Design your HomeFund card</h2><p class="card-note">Cosmetic simulated card only. It cannot be used for payment.</p><form id="hfDesign" class="form"><label>Theme<select name="theme"><option value="navy">HomeFund Navy</option><option value="midnight">Midnight</option><option value="ice">Ice</option><option value="emerald">Emerald</option><option value="rose">Rose</option></select></label><button class="primary">Save card design</button></form><button class="secondary" id="hfNewNumber">Generate new simulated card number</button>`);q('#hfDesign').theme.value=p.theme||'navy';q('#hfDesign').onsubmit=e=>{e.preventDefault();save({theme:new FormData(e.target).get('theme')});applyPrefs();close();toast('Card design saved.')};q('#hfNewNumber').onclick=()=>{save({number:fakeNumber()});applyPrefs();toast('New simulated number generated.')};}
function addMoney(){if(typeof incomeModal==='function')return incomeModal();q('[data-action="income"]')?.click()}
function sharedCard(){const shared=(goals||[]).filter(g=>g.is_shared).reduce((a,g)=>a+Number(g.current_amount||0),0);modal(`<p class="kicker">SHARED HOUSEHOLD CARD</p><h2>HomeFund Family Card</h2><div class="hf-shared-card"><b>HOMEFUND FAMILY</b><strong>${money(shared)}</strong><span>Shared tracked family funds</span><em>SIMULATED • NOT FOR PAYMENT</em></div><p class="card-note">This view represents shared HomeFund family funds. It does not create or move real money.</p>`)}
function center(){modal(`<p class="kicker">HOMEFUND WALLET</p><h2>Card Center</h2><div class="hf-card-menu"><button id="hfDesignBtn">✦ Card Designer</button><button id="hfMoneyBtn">＋ Quick Add Money</button><button id="hfSharedBtn">⌂ Shared Household Card</button><button id="hfFlipBtn">↻ Flip Card</button></div><p class="card-note">All HomeFund cards are simulated tracking tools and cannot be used for payment.</p>`);q('#hfDesignBtn').onclick=designer;q('#hfMoneyBtn').onclick=addMoney;q('#hfSharedBtn').onclick=sharedCard;q('#hfFlipBtn').onclick=()=>{close();q('.bank-card')?.classList.toggle('flipped')}}
function bind(){decorate();const c=q('#cardControlsBtn');if(c)c.onclick=center;const f=q('#freezeCardBtn');if(f&&!f.dataset.fun){f.dataset.fun='1';f.addEventListener('click',()=>{const card=q('.bank-card');card?.classList.add('hf-freeze-burst');setTimeout(()=>card?.classList.remove('hf-freeze-burst'),900)})}}
window.HomeFundPaydayAnimation=amount=>{const card=q('.bank-card');if(!card)return;const b=document.createElement('div');b.className='hf-payday-pop';b.textContent=`+${money(amount)} PAYDAY`;card.appendChild(b);card.classList.add('hf-payday');setTimeout(()=>{b.remove();card.classList.remove('hf-payday')},2200)};
const css=document.createElement('style');css.textContent=`.hf-flip-card{perspective:1000px;cursor:pointer;background:transparent!important;position:relative}.hf-card-inner{position:relative;width:100%;height:100%;min-height:210px;transition:transform .65s cubic-bezier(.2,.7,.2,1);transform-style:preserve-3d}.hf-flip-card.flipped .hf-card-inner{transform:rotateY(180deg)}.hf-card-face{position:absolute;inset:0;backface-visibility:hidden;border-radius:inherit;padding:inherit}.hf-card-front{background:inherit}.hf-card-back{transform:rotateY(180deg);background:#071b33;color:#fff;padding:24px;display:flex;flex-direction:column;gap:12px}.magstripe{height:42px;background:#111;margin:8px -24px 8px}.hf-card-back small{opacity:.7}.hf-mini{margin-top:auto}.bank-card[data-theme=midnight] .hf-card-front{background:linear-gradient(135deg,#05070c,#252a35)}.bank-card[data-theme=ice] .hf-card-front{background:linear-gradient(135deg,#dceef8,#7eaac4);color:#071b33}.bank-card[data-theme=emerald] .hf-card-front{background:linear-gradient(135deg,#073c32,#15906d)}.bank-card[data-theme=rose] .hf-card-front{background:linear-gradient(135deg,#5c243b,#b85f7c)}.hf-freeze-burst:after{content:'❄ CARD FROZEN';position:absolute;inset:0;z-index:20;border-radius:inherit;background:rgba(220,242,255,.82);backdrop-filter:blur(3px);display:grid;place-items:center;color:#174f70;font-weight:900;letter-spacing:2px;animation:hfFrost .9s ease forwards}@keyframes hfFrost{0%{opacity:0;transform:scale(.96)}35%{opacity:1;transform:scale(1)}100%{opacity:0}}.hf-payday{animation:hfGlow 1.1s ease 2}@keyframes hfGlow{50%{transform:translateY(-3px);filter:brightness(1.18)}}.hf-payday-pop{position:absolute;z-index:30;left:50%;top:45%;transform:translate(-50%,-50%);background:#fff;color:#087a55;border-radius:999px;padding:10px 16px;font-weight:900;box-shadow:0 12px 35px #0003;white-space:nowrap}.hf-card-menu{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}.hf-card-menu button{padding:16px;border:1px solid #dce3eb;border-radius:12px;background:#f7f9fc;font-weight:800;text-align:left;cursor:pointer}.hf-shared-card{background:linear-gradient(135deg,#071b33,#164d79);color:#fff;border-radius:18px;padding:24px;min-height:170px;display:flex;flex-direction:column;gap:12px}.hf-shared-card strong{font-size:30px}.hf-shared-card span,.hf-shared-card em{font-size:10px;opacity:.75}.hf-shared-card em{margin-top:auto}@media(max-width:600px){.hf-card-menu{grid-template-columns:1fr}}`;document.head.appendChild(css);
window.addEventListener('load',()=>setTimeout(bind,900));setInterval(()=>{if(session&&profile)bind()},2500);
})();